export { cartesianProduct } from './cartesian-product'
export { N } from './constants'
export { neighbours } from './neighbours'
export { szudzik, unszudzik } from './szudzik'
export { tile } from './tile'
export { toPosition } from './to-position'
export { toSquare } from './to-square'
export { isolate } from './isolate'
export type { Model } from './types'
