name = "app"
main = "./dist/worker/index.mjs"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-02-22"
no_bundle = false

[build]
command = "node ./scripts/build.mjs"

[site]
bucket = "./dist/client/"
