name = "app"
main = "./dist/worker/entry-server.js"
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2024-09-23"
no_bundle = false
preserve_file_names = true
assets = { directory = "dist/client" }

[build]
command = "pnpm exec tsx ./scripts/build.js"
watch_dir = ["./src"]
